cloud:
  aws:
    credentials:
      instanceProfile: true # aws configure list로 확인한 key들을 사용
    s3:
      bucket:
        name: "devshare-pangnem"
        imageDir: "images"
    region:
      static: "ap-northeast-2"
    stack: # CloudFormation 구성 설정 해제
      auto: false
